### ISSUE TITLE
[UNDO-REDO] Works by pixels

### ISSUE THREAD

**Issue by FromSi** [rgab1508/PixelCraft#36]
It is not convenient to work when UNDO-REDO does not work by my history. Is this how it should work?
![Peek 2021-01-09 17-27](https://user-images.githubusercontent.com/22871855/104090246-ba12bd00-529f-11eb-8d54-38f8ed2521c6.gif)

**Comment by theabbie** [comment]
@FromSi We know that  undo/redo is not perfect, we will try to improve it.
