### ISSUE TITLE
Gray and blocked layer when creating a grid

### ISSUE THREAD

**Issue by FromSi** [rgab1508/PixelCraft#38]
Two questions:

1. Why can't I recreate the grid? (reloading page).
2. Why is there no grid constraint? I think that at this stage of development of the project and its functionality, the norm will be a 124x124 grid.

I think it would be logical. You can make templates according to the size of the grids and get rid of the constant input of numbers (taking into account the fact that you can leave the previous functionality with a certain restriction).

![Peek 2021-01-09 23-48](https://user-images.githubusercontent.com/22871855/104104998-8c486b00-52d5-11eb-8779-6f1329b9573b.gif)

![Screenshot_20210109_235528](https://user-images.githubusercontent.com/22871855/104105073-f7923d00-52d5-11eb-96ee-7129162939f6.png)

**Comment by theabbie** [comment]
@FromSi You can save progress in this version https://rgab1508.github.io/PixelCraft

Grid constraint is about 128 X 128, it is not added but it works smoothly until that dimension.

**Comment by FromSi** [comment]
Indeed, the new version already has "new". I do not know if it is useful to leave issue to solve the gray layer problem?
I think we should keep it. Thanks

**Comment by theabbie** [comment]
@FromSi The Gray layer is because the grid dimensions were too big and it didn't get painted white because of too much processing.
