### ISSUE TITLE
Impossible to create a freehand, transparent line of consistent color

### ISSUE THREAD

**Issue by mrfoogles** [rgab1508/PixelCraft#40]
If you draw freehand with a transparent color, the pencil redraws on top of the transparent again so that you get a mottled line of a bunch of different levels.  This makes the transparency feature pretty useless.

**Comment by theabbie** [comment]
@mrfoogles That is a property of canvas, drawing transparent over other will create this, in most cases, that's the expected behaviour. We will try to look into it. Thanks for informing.

**Comment by mrfoogles** [comment]
I made a pull request, anyway.  I probably shouldn't have made the issue, sorry.
