### ISSUE TITLE
Stop Spamming on EchoJS!

### ISSUE THREAD

**Issue by shadowtime2000** [rgab1508/PixelCraft#52]
Stop spamming on EchoJS!

Also stop using bots to get more upvotes. Its not cool and now very few people actually care about this project and you are drowning out the things that are actually nice things to look at. 

![image](https://user-images.githubusercontent.com/66655515/106365392-2bb3b900-62ea-11eb-8ef8-577c4c8ee6c8.png)

**Comment by shadowtime2000** [comment]
talking to @theabbie.

**Comment by theabbie** [comment]
@shadowtime2000 sure
