### ISSUE TITLE
error when trying to install PWA via menu

### ISSUE THREAD

**Issue by maks** [rgab1508/PixelCraft#53]
When trying to use the demo on https://rgab1508.github.io/PixelCraft/ and using the "Install PWA" hamburger menu I get the following error:  

![Screenshot from 2021-02-25 09-38-30](https://user-images.githubusercontent.com/71999/109076010-0893f200-774e-11eb-9e28-85151c2d2934.png)

This is using:
Google Chrome | 88.0.4324.182 (Official Build) (64-bit)
OS | Linux

**Comment by maks** [comment]
Same thing happens on https://pixelcraft.web.app/ too.

**Comment by maks** [comment]
Installing via Chromes own menu option "Install PixelArt" from https://pixelcraft.web.app/ does work.

**Comment by theabbie** [comment]
@maks Thanks for informing, it used to work earlier, will try to fix it.
